### ISSUE TITLE
Spaces in colorbar annotation

### ISSUE THREAD

**Issue by s7stschr** [GenericMappingTools/pygmt#391] opened 2020-01-17 17:05 UTC
Hello and thanks for the great work! I have a small request of which I'm not sure if I'm just missing something easy or if it's just not implemented.

Is there already a convenient way to make a colorbar annotation with more than 1 word, i.e. spaces in it? Right now when I use e.g. fig.colorbar(frame='paf+lheight[m]'), I cannot just make a space between height and [m]:
GMTCLibError: Module 'colorbar' failed with status code 71:
colorbar [ERROR]: Syntax error: No input files are allowed.

Best Regards,
Stefan

**Comment by seisman** [comment] 2020-01-17 18:42
That's a known issue. Currently, you have to enclose the string with quotes, e.g.

```
frame='paf+l"height [m]"'
```

Closed as duplicate of #247.

**Closed by seisman** 2020-01-17 18:42 UTC
