### ISSUE TITLE
Auto-legend crashes if more than 64 legend entries are given

### ISSUE THREAD

**Issue by maihao14** [GenericMappingTools/pygmt#1461] opened 2021-08-23 04:25 UTC
**Description of the problem**
I tried to display GSN network stations on a global network. All good before I add a legend to show different networks. It will lead to IDE console restart or terminal stop.

**Full code that generated the error**

```
#%% import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from unicodedata import normalize
#%% read html
# =============================================================================
table_MN = pd.read_html('https://earthquake.usgs.gov/monitoring/operations/network.php?virtual_network=GSN')
print(f'Total tables: {len(table_MN)}')
 
#%% print and save
df = table_MN[0]
# df.head()
# df.to_csv("gsn.csv")
# =============================================================================
#%% read csv
#df = pd.read_csv("gsn.csv")

#%% plot global station

import pygmt


# Set Global scale region
region = 'g'
# Create pygmt.Figure
fig = pygmt.Figure()
grid = pygmt.datasets.load_earth_relief(resolution="03m",region='g')
fig.grdimage(region='g',grid=grid, projection="Y35/30/12c", frame="a", cmap="geo")

net_name = df['Network Code'].unique() 
# create colorlist
colorsList = {}
for i in net_name:
#for i in range(len(net_name)):
    colorsList[i] = '#%06X' % np.random.randint(0, 0xFFFFFF)
#%%
for idx, dff in df.iterrows():
    fig.plot(
        x=dff["Longitude"],
        y=dff["Latitude"],
        style="i3p",
        color=colorsList[dff['Network Code']],
        pen="black",
        label=dff['Network Code']
    )
# both failed
# I want to put legend outside map on middle right
fig.legend(position="JMR+o0.2c",box=True)
#fig.legend()
fig.show()
fig.savefig('GSN.png', crop=True, dpi=300)
```

**Full error message**

```
segmentation fault  python gsn.py
```

**System information**

Please paste the output of `python -c "import pygmt; pygmt.show_versions()"`:

```
PyGMT information:
  version: v0.4.0
System information:
  python: 3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09)  [Clang 11.1.0 ]
  executable: /Users/hao/opt/anaconda3/envs/qltest/bin/python
  machine: macOS-10.16-x86_64-i386-64bit
Dependency information:
  numpy: 1.21.0
  pandas: 1.3.0
  xarray: 0.18.2
  netCDF4: 1.5.7
  packaging: 21.0
  ghostscript: 9.54.0
  gmt: 6.2.0
GMT library information:
  binary dir: /Users/hao/opt/anaconda3/envs/qltest/bin
  cores: 16
  grid layout: rows
  library path: /Users/hao/opt/anaconda3/envs/qltest/lib/libgmt.dylib
  padding: 2
  plugin dir: /Users/hao/opt/anaconda3/envs/qltest/lib/gmt/plugins
  share dir: /Users/hao/opt/anaconda3/envs/qltest/share/gmt
  version: 6.2.0
```

**Comment by seisman** [comment] 2021-08-23 04:44
I can reproduce your issue. Perhaps it's because you're adding too many entries to the legend?

I changed this line `for idx, dff in df.iterrows():` to `for idx, dff in list(df.iterrows())[0:10]:` to plot only the first 10 stations, and I got the figure below:

![GSN](https://user-images.githubusercontent.com/3974108/130391001-2b9fd405-c8ea-4fc7-a154-0b92bb75230f.png)

As you can see, the "CU" entry appears multiple times in the legend. I don't think this is what you want.

**Comment by maihao14** [comment] 2021-08-23 04:49
> I can reproduce your issue. Perhaps it's because you're adding too many entries to the legend?
> 
> I changed this line `for idx, dff in df.iterrows():` to `for idx, dff in list(df.iterrows())[0:10]:` to plot only the first 10 stations, and I got the figure below:
> 
> ![GSN](https://user-images.githubusercontent.com/3974108/130391001-2b9fd405-c8ea-4fc7-a154-0b92bb75230f.png)
> 
> As you can see, the "CU" entry appears multiple times in the legend. I don't think this is what you want.

**Comment by maihao14** [comment] 2021-08-23 04:52
Thanks for your quick reply. Yes, that's not what I want. I want to show the labels as network names : 
array(['CU', 'GT', 'IC', 'II', 'IU'], dtype=object) 
Thus, only 5 unique labels should be there. 
I have no idea why fig.plot(label=dff['Network Code'])  cannot do this.
Could you give me more explains about this?

**Comment by seisman** [comment] 2021-08-23 05:01
The problem is the `plot` module doesn't remove duplicated legend entries. Let's assume that you have 5 networks and 100 stations. Your current code calls the `plot` function 100 times using the `label` parameter, so GMT will add 100 legend entries when `legend` is called.

I think the easiest way is to loop over all the 5 networks, get stations that belongs to a single network code, and call the `plot` function to plot many stations at one time.

**Comment by maihao14** [comment] 2021-08-23 05:04
Got it, thanks for your help!  I will try this solution and post the codes here soon.

**Comment by seisman** [comment] 2021-08-23 05:20
@maihao14 Your issue report helps find an upstream GMT bug. I have reported it in the GMT repository at https://github.com/GenericMappingTools/gmt/issues/5698. Thanks.

**Comment by maihao14** [comment] 2021-08-23 07:10
**Problem Solved!**
Thanks for @seisman, run loop in networks could help fix the legend() problem (use less than 65 entries).
Here's the scripts:

```
#%% import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from unicodedata import normalize
#%% read html
# =============================================================================
table_MN = pd.read_html('https://earthquake.usgs.gov/monitoring/operations/network.php?virtual_network=GSN')
print(f'Total tables: {len(table_MN)}')
 
#%% print and save
df = table_MN[0]
# df.head()
# df.to_csv("gsn.csv")
# =============================================================================
#%% read csv
#df = pd.read_csv("gsn.csv")

#%% plot global station

import pygmt


# Set Global scale region
region = 'g'
# Create pygmt.Figure
fig = pygmt.Figure()
grid = pygmt.datasets.load_earth_relief(resolution="03m",region='g')
fig.grdimage(region='g',grid=grid, projection="Y35/30/12c", frame="a", cmap="geo")

net_name = df['Network Code'].unique() 
# create colorlist
colorsList = {}
for i in net_name:
#for i in range(len(net_name)):
    colorsList[i] = '#%06X' % np.random.randint(0, 0xFFFFFF)
#%% loop in network [This is an update]
for net in net_name:
    fig.plot(
        x=df[df['Network Code'] == net]['Longitude'],
        y=df[df['Network Code'] == net]['Latitude'],
        style="i3p",
        color=colorsList[net],
        pen="black",
        label=net
    )    
fig.legend(position="JMR+o0.2c",box=True)
fig.show()
fig.savefig('GSN.png', crop=True, dpi=300)
```
![GSN](https://user-images.githubusercontent.com/28862378/130405352-8f709df9-9ae2-4096-83db-3000b7865b0a.png)

**Comment by seisman** [comment] 2021-08-24 03:29
I'm closing the issue because the upstream bug has been fixed.

**Closed by seisman** 2021-08-24 03:29 UTC
Labels: bug, upstream
