### ISSUE TITLE
pygmt.Figure.grdcontour kills kernel after running for a long time

### ISSUE THREAD

**Issue by saeedmohanna** [GenericMappingTools/pygmt#1927] opened 2022-05-22 07:41 UTC
I am reading in a 722x480 array and trying to plot it with pygmt.Figure.grdcontour. The code runs for a long time before killing the kernel. I don't think this is a memory issue because I was able to plot a 360x240 array with grdcontour instantly. Is it stuck in some loop somewhere in the source code? 

Please see attached. One shows the code outputting the desired result without contours (blocked out by white rectangle ) and the other shows the case with grdcontour being used. 

Any help on this issue would be appreciated.

Without grdcontour:
<img width="551" alt="Screen Shot 2022-05-22 at 12 40 00 AM" src="https://user-images.githubusercontent.com/51676976/169684306-3103ab7c-bcd7-4888-b12d-aa79195cdfff.png">

With grdcontour:
<img width="552" alt="Screen Shot 2022-05-22 at 12 41 41 AM" src="https://user-images.githubusercontent.com/51676976/169684351-75adc530-6f86-4484-874a-85e901383249.png">

**Comment by seisman** [comment] 2022-05-22 08:35
@saeedmohanna Can you share with us the "src_inversion_5.nc" file, so that we can try to reproduce the issue?

**Comment by saeedmohanna** [comment] 2022-05-22 09:06
@seisman Unfortunately github doesn't let me attach the file directly. Here is a google drive link: https://drive.google.com/file/d/1Ll2qYqeOM882mV3wrjuwYFSSSgSFwyDR/view?usp=sharing

**Comment by seisman** [comment] 2022-05-22 15:00
Running the following GMT command, it also takes forever for me.
`gmt grdcontour src_inversion_5.nc -A2 -C2 -pdf map`

@PaulWessel Is this an upstream bug or is there something wrong with the grid.

I see something weird like:
```
gmt [INFORMATION]: No range attribute, guessing registration to be pixel
gmt [INFORMATION]: netCDF grid src_inversion_5.nc has no default CPT.
gmt [INFORMATION]: netCDF grid src_inversion_5.nc information has zmin = zmax = NaN. Reset to 0/0.
gmt [INFORMATION]: Cartesian input grid
```

**Comment by PaulWessel** [comment] 2022-05-22 15:03
I will have a look on the flight.  It is probably a non-COARDS-compliant grid of some sort.

**Comment by seisman** [comment] 2022-05-24 01:42
@saeedmohanna FYI, the upstream bug is being tracked in https://github.com/GenericMappingTools/gmt/issues/6738

**Comment by seisman** [comment] 2024-03-15 14:01
I believe the upstream bug has been fixed in https://github.com/GenericMappingTools/gmt/issues/6738, and the command at https://github.com/GenericMappingTools/pygmt/issues/1927#issuecomment-1133914464 now works for me using the GMT dev version. Closing the issue.

**Closed by seisman** 2024-03-15 14:01 UTC
Labels: upstream
