### ISSUE TITLE
Drawing rectangles

### ISSUE THREAD

**Issue by Nasuyo** [GenericMappingTools/pygmt#392] opened 2020-01-20 15:41 UTC
Hello,

When trying to plot (fig.plot()) rectangles, basically nothing happens..^^
Following code -- with squres -- works:

```python
fig = pygmt.Figure()
fig.coast(region=[0, 26, 44, 62], projection='S13/90/6i', frame="ag", shorelines="0.3p,black", borders="1/0.5p,black")
fig.plot(10, 50, style='s1')
fig.show()
```

This should do the exact same thing, shouldn't it?:

```python
fig = pygmt.Figure()
fig.coast(region=[0, 26, 44, 62], projection='S13/90/6i', frame="ag", shorelines="0.3p,black", borders="1/0.5p,black")
fig.plot(10, 50, style='r1/1')
fig.show()
```

Problem: No rectangle is drawn. Alterations fomo the style command like 'r1', 'r1,1', 'r1c', 'r1c/1c' etc. neither work.

Problem 2: Substituting r by R for a rounded rectangle produces an error:

```python-traceback
Module 'psconvert' failed with status code 78:
psconvert [ERROR]: System call [gs -q -dSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true '/home/schroeder/.gmt/sessions/gmt6.20169/gmt_124.ps-' 2> '/home/schroeder/.gmt/sessions/gmt6.20169/psconvert_20169c.bb'] returned error 256.
```

I'm not sure whether this is actually a bug or just my own lack of knowledge.

Thanks in advance,
Stefan

**Comment by weiji14** [comment] 2020-03-11 03:42
Hi Nasuyo,

Sorry for the really late reply, only got back into the flow quite recently :flushed:. I've had a look at the code and you're right, it only works with squares because you can pass a size argument directly into the `style` (e.g. `style='s1'` for a square of size 1). For rectangles it's a bit harder as GMT requires the length and width to be in the data column (rather than as you tried, 'r1/1'). See also https://docs.generic-mapping-tools.org/latest/plot.html#s.

One solution I can think of at the moment would be to put your x, y, length, width numbers into a textfile, and call something like `pygmt.plot(data="file.txt", style="r")`. Ideally though, we'll need to fix the relevant code here https://github.com/GenericMappingTools/pygmt/blob/320a7289c31a01e2b8b78ca83d2bbc3d258ecea6/pygmt/base_plotting.py#L321-L436

Alternatively, if you know the West/South/East/North coordinates of your area of interest, you can supply them directly and use `style="r+s"` like so:

```python
import numpy as np
import pygmt

fig = pygmt.Figure()
fig.coast(region=[0, 26, 44, 62], projection='S13/90/6i', frame="ag", shorelines="0.3p,black", borders="1/0.5p,black")
fig.plot(data=np.array([[5,47,15,52]]), style='r+s', pen="3p,yellow")
fig.show()
```
gives:
![Yellow rectangle drawn using pygmt](https://user-images.githubusercontent.com/23487320/76380125-e24b3a00-63b6-11ea-8f54-d4129b19bc45.png)

**Comment by seisman** [comment] 2020-09-13 02:31
FYI, GMT recently allows specifying rectangle's width and height from command line in https://github.com/GenericMappingTools/gmt/pull/4164. It will be available in GMT 6.2.0.

Before that, the rectangle width and height must be given from the input data.

**Comment by meghanrjones** [comment] 2021-02-11 17:56
I just tested this with the development version of gmt (6.2.0_d8a7766_2021.02.11).

This now produces a rectangle:
```
fig = pygmt.Figure()
fig.coast(region=[0, 26, 44, 62], projection='S13/90/6i', frame="ag", shorelines="0.3p,black", borders="1/0.5p,black")
fig.plot(10, 50, style='r1/2')
fig.show()
```
And the rounded rectangle style produced an error because the corner radius is required. This works for a rounded rectangle:
```
fig = pygmt.Figure()
fig.coast(region=[0, 26, 44, 62], projection='S13/90/6i', frame="ag", shorelines="0.3p,black", borders="1/0.5p,black")
fig.plot(10, 50, style='R1/2/0.5')
fig.show()
```
Does the issue stay open until GMT 6.2 is released or does it get closed as soon as the problem is fixed in the main gmt branch?

**Comment by seisman** [comment] 2021-02-11 17:58
We will keep the issue open until we bump the minimum required GMT version to 6.2.0 in PyGMT v0.4.0.

**Comment by meghanrjones** [comment] 2021-02-11 18:04
Would it be possible to use a tag for these types of issues (i.e., upstream problems that are solved but require an update to the minimum required GMT version)? In reading through PyGMT issues, it appears there are at least a couple issues of these currently open. I think a tag would help for keeping track and quickly identifying which issues do not require any action.

**Comment by weiji14** [comment] 2021-02-11 22:13
> Would it be possible to use a label for these types of issues (i.e., upstream problems that are solved but require an update to the minimum required GMT version)? In reading through PyGMT issues, it appears there are at least a couple of this type of issue currently open. I think a tag would help for keeping track and quickly identifying which issues do not require any action.

Yeah there are quite a few of these. I think labeling it 'upstream' and adding it to the v0.4.0 milestone should suffice, but feel free to suggest a new label.

**Comment by weiji14** [comment] 2021-06-02 00:23
> I just tested this with the development version of gmt (6.2.0_d8a7766_2021.02.11).
> 
> This now produces a rectangle:
> 
> ```
> fig = pygmt.Figure()
> fig.coast(region=[0, 26, 44, 62], projection='S13/90/6i', frame="ag", shorelines="0.3p,black", borders="1/0.5p,black")
> fig.plot(10, 50, style='r1/2')
> fig.show()
> ```
> 
> And the rounded rectangle style produced an error because the corner radius is required. This works for a rounded rectangle:
> 
> ```
> fig = pygmt.Figure()
> fig.coast(region=[0, 26, 44, 62], projection='S13/90/6i', frame="ag", shorelines="0.3p,black", borders="1/0.5p,black")
> fig.plot(10, 50, style='R1/2/0.5')
> fig.show()
> ```
> 
> Does the issue stay open until GMT 6.2 is released or does it get closed as soon as the problem is fixed in the main gmt branch?

Perhaps add a new gallery example to mention the `style='r1/2'` way of drawing rectangles? Then we can close this issue.

**Comment by core-man** [comment] 2021-06-02 07:33
> Perhaps add a new gallery example to mention the `style='r1/2'` way of drawing rectangles? Then we can close this issue.

Could I help with this example?

**Comment by weiji14** [comment] 2021-06-02 08:46
> > Perhaps add a new gallery example to mention the `style='r1/2'` way of drawing rectangles? Then we can close this issue.
> 
> Could I help with this example?
> 
> 

Yes please, go for it! I'll assign this issue to you @core-man.

**Comment by seisman** [comment] 2021-06-03 00:03
Please note that we already have an example for rectangles (https://www.pygmt.org/latest/gallery/symbols/multi_parameter_symbols.html), but in this example we read the "sizes" from the input file, rather than in the `style` parameter.

I feel we can simply update that example, rather than adding a new gallery example.

**Comment by Nasuyo** [comment] 2021-06-07 07:25
Hello,
    I am currently out of office. I will be back on Monday, 07.06.
    Stefan

**Closed** 2021-06-19 23:10 UTC
Labels: bug, documentation, upstream
