### ISSUE TITLE
pygmt will not configure the PS_CONVERT parameter

### ISSUE THREAD

**Issue by xueke114** [GenericMappingTools/pygmt#2870] opened 2023-12-12 02:34 UTC
### Description of the problem

When executing `fig.savefig()` or `fig.show()`, the DEBUG message shows that the value of the PS_CONVERT parameter is not taken with it when the `gs` command is run.

### Minimal Complete Verifiable Example

```python
import pygmt

fig = pygmt.Figure()
pygmt.config(PS_CONVERT="C-I/home/xueke/.gmt/", FONT_TITLE=",41,")
fig.coast(region="g", land="gray", frame=["+t世界", "afg"], projection="H10c")
fig.savefig("world.png", verbose="d")
```

### Full error message

```python-traceback
psconvert [DEBUG]: gmt_check_executable: Pass to popen: [gs --version 2> /dev/null]
psconvert [DEBUG]: gs --version 2> /dev/null was successful
psconvert [DEBUG]: Ghostscript version: 9.55.0
psconvert [DEBUG]: Use PS filename /home/xueke/.gmt/sessions/gmt_session.76422/gmt_1.ps-
psconvert [DEBUG]: Hidden PS file /home/xueke/.gmt/sessions/gmt_session.76422/gmt_1.ps- found
psconvert [DEBUG]: Complete partial PS file /home/xueke/.gmt/sessions/gmt_session.76422/gmt_1.ps-
psconvert [DEBUG]: Size of half-baked PS file = 135172.
psconvert [DEBUG]: Fattened up PS file /home/xueke/.gmt/sessions/gmt_session.76422/gmt_1.ps-
psconvert [INFORMATION]: Processing /home/xueke/.gmt/sessions/gmt_session.76422/gmt_1.ps-...
psconvert [INFORMATION]: Find HiResBoundingBox ...
psconvert [DEBUG]: Running: gs -q -dNOSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true '/home/xueke/.gmt/sessions/gmt_session.76422/gmt_1.ps-' 2> '/home/xueke/.gmt/sessions/gmt_session.76422/psconvert_76422c.bb'
psconvert [INFORMATION]: Figure dimensions: Width: 297.99 points [10.5124 cm]  Height: 180.738 points [6.37603 cm]
psconvert [DEBUG]: Delete /home/xueke/.gmt/sessions/gmt_session.76422/psconvert_76422c.bb
psconvert [INFORMATION]: [346.122 359.334 644.112 540.072]...
psconvert [INFORMATION]: Convert to PNG...
psconvert [DEBUG]: Running: gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=2 -sDEVICE=png16m  -g1242x754 -r300 -sOutputFile='hello.png' '/home/xueke/.gmt/sessions/gmt_session.76422/psconvert_76422d.eps'
psconvert [DEBUG]: Delete /home/xueke/.gmt/sessions/gmt_session.76422/psconvert_76422d.eps
psconvert [DEBUG]: Final input buffer length was 256
```

### System information

```bash
PyGMT information:
  version: v0.10.0
System information:
  python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
  executable: /home/xueke/WorkspaceOnline/SoilMoistureResearch/.venv/bin/python
  machine: Linux-6.2.0-37-generic-x86_64-with-glibc2.35
Dependency information:
  numpy: 1.26.2
  pandas: 2.1.4
  xarray: 2023.12.0
  netCDF4: 1.6.5
  packaging: 23.2
  contextily: None
  geopandas: 0.14.1
  IPython: None
  rioxarray: None
  ghostscript: 9.55.0
GMT library information:
  cores: 24
  grid layout: rows
  image layout: 
  library path: /usr/lib/x86_64-linux-gnu/libgmt.so
  padding: 2
  plugin dir: /usr/lib/x86_64-linux-gnu/gmt/plugins
  share dir: /usr/share/gmt
  version: 6.3.0
```

**Comment by xueke114** [comment] 2023-12-12 02:39
But specifying the `gs_option` parameter in `fig.savefig()` works fine.

```python
import pygmt

fig = pygmt.Figure()
pygmt.config(FONT_TITLE=",41,")
fig.coast(region="g", land="gray", frame=["+t世界", "afg"], projection="H10c")
fig.savefig("world.png", gs_option="-I/home/xueke/.gmt/", verbose="d")
```

```text
psconvert [DEBUG]: gmt_check_executable: Pass to popen: [gs --version 2> /dev/null]
psconvert [DEBUG]: gs --version 2> /dev/null was successful
psconvert [DEBUG]: Ghostscript version: 9.55.0
psconvert [DEBUG]: Use PS filename /home/xueke/.gmt/sessions/gmt_session.78045/gmt_1.ps-
psconvert [DEBUG]: Hidden PS file /home/xueke/.gmt/sessions/gmt_session.78045/gmt_1.ps- found
psconvert [DEBUG]: Complete partial PS file /home/xueke/.gmt/sessions/gmt_session.78045/gmt_1.ps-
psconvert [DEBUG]: Size of half-baked PS file = 135172.
psconvert [DEBUG]: Fattened up PS file /home/xueke/.gmt/sessions/gmt_session.78045/gmt_1.ps-
psconvert [INFORMATION]: Processing /home/xueke/.gmt/sessions/gmt_session.78045/gmt_1.ps-...
psconvert [INFORMATION]: Find HiResBoundingBox ...
psconvert [DEBUG]: Running: gs -q -dNOSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill  -I/home/xueke/.gmt/ -dMaxBitmap=2147483647 -dUseFastColor=true '/home/xueke/.gmt/sessions/gmt_session.78045/gmt_1.ps-' 2> '/home/xueke/.gmt/sessions/gmt_session.78045/psconvert_78045c.bb'
psconvert [INFORMATION]: Figure dimensions: Width: 297.99 points [10.5124 cm]  Height: 180.108 points [6.35381 cm]
psconvert [DEBUG]: Delete /home/xueke/.gmt/sessions/gmt_session.78045/psconvert_78045c.bb
psconvert [INFORMATION]: [346.122 359.334 644.112 539.442]...
psconvert [INFORMATION]: Convert to PNG...
psconvert [DEBUG]: Running: gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2  -I/home/xueke/.gmt/ -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=2 -sDEVICE=png16m  -g1242x751 -r300 -sOutputFile='world.png' '/home/xueke/.gmt/sessions/gmt_session.78045/psconvert_78045d.eps'
psconvert [DEBUG]: Delete /home/xueke/.gmt/sessions/gmt_session.78045/psconvert_78045d.eps
psconvert [DEBUG]: Final input buffer length was 256
```

**Comment by seisman** [comment] 2023-12-12 05:44
As documented by the GMT documentation (https://docs.generic-mapping-tools.org/dev/gmt.conf#term-PS_CONVERT):

> Comma-separated list of optional module arguments that we should supply when [psconvert](https://docs.generic-mapping-tools.org/dev/psconvert.html) is called implicitly under modern mode [A]. Ignored when psconvert is called on the command line explicitly. The option arguments must be listed without their leading option hyphen.

So this configuration is ignored when psconvert is called on the command line explicitly. This is exactly what `Figure.savefig` does. So, this is the expected behavior.

**Comment by xueke114** [comment] 2023-12-12 07:03
> As documented by the GMT documentation (https://docs.generic-mapping-tools.org/dev/gmt.conf#term-PS_CONVERT):
> 
> > Comma-separated list of optional module arguments that we should supply when [psconvert](https://docs.generic-mapping-tools.org/dev/psconvert.html) is called implicitly under modern mode [A]. Ignored when psconvert is called on the command line explicitly. The option arguments must be listed without their leading option hyphen.
> 
> So this configuration is ignored when psconvert is called on the command line explicitly. This is exactly what `Figure.savefig` does. So, this is the expected behavior.

I see. Thank you.

**Comment by yvonnefroehlich** [comment] 2024-01-20 19:39
> As documented by the GMT documentation (https://docs.generic-mapping-tools.org/dev/gmt.conf#term-PS_CONVERT):
> 
> > Comma-separated list of optional module arguments that we should supply when [psconvert](https://docs.generic-mapping-tools.org/dev/psconvert.html) is called implicitly under modern mode [A]. Ignored when psconvert is called on the command line explicitly. The option arguments must be listed without their leading option hyphen.
> 
> So this configuration is ignored when psconvert is called on the command line explicitly. This is exactly what `Figure.savefig` does. So, this is the expected behavior.

So this is not a bug, and we can close this issue, or?

**Closed** 2024-01-21 05:05 UTC
Labels: bug
