### ISSUE TITLE
how to plot tick marks inside the plot

### ISSUE THREAD

**Issue by vira12x** [GenericMappingTools/pygmt#2150] opened 2022-10-08 11:12 UTC
### Description of the problem

I am plotting a map and it takes the default config parameters.I just want to plot the tick marks inside the plot. I tried with t option but couldnot find any solution. 
May be its a tick rotation by some degree
please help
Thanks

### Full error message

```python-traceback
problrm on plotting tick marks inside the plot
```

### System information

```bash
ubuntu 22.04
newversion of pygmt
```

**Comment by weiji14** [comment] 2022-10-08 11:39
Try using `MAP_FRAME_TICK="inside"` like so https://github.com/weiji14/nzasc2021/blob/main/key_figure.py#L161-L161

**Comment by seismoprocess** [comment] 2022-10-08 12:00
Actually I just want the tick values to be in outside and only the tick marks inside the plot.
Your suggested command plot bothe tick values and marks insde the plot.
Please suggest some better solution
Thanks

**Comment by vira12x** [comment] 2022-10-08 12:06
@weiji14 when i set this command both the tick values and tick marks are plotted inside the plot.But i want the values to be in outside and tick marks to be inside the plot.
Something like this https://mathematica.stackexchange.com/questions/2601/labels-and-tickmarks-inside-frame

Please suggest a solution.Thanks

**Comment by seisman** [comment] 2022-10-08 13:03
> But i want the values to be in outside and tick marks to be inside the plot.

You can do it by setting a negative tick length: 
```python
with pygmt.config(MAP_TICK_LENGTH="-10p"): 
     fig.basemap(...)
```

**Comment by yvonnefroehlich** [comment] 2022-10-08 16:25
This issue is related to or a duplicate of this forum post https://forum.generic-mapping-tools.org/t/how-to-rotate-the-tick-marks-so-that-it-will-be-inside-the-plot/3336 (https://forum.generic-mapping-tools.org/t/how-to-rotate-the-tick-marks-so-that-it-will-be-inside-the-plot/3336/6?u=yvonnefroehlich). Thus I think we can close this issue here.

**Closed** 2022-10-08 16:26 UTC
Labels: question
