### ISSUE TITLE
fig.show() not work

### ISSUE THREAD

**Issue by zengxianghang** [GenericMappingTools/pygmt#1159] opened 2021-04-02 00:57 UTC
**Description of the problem**
After the following code runs, the figure cannot be displayed automatically.

**Full code that generated the error**

```python
import pygmt

pygmt.show_versions()
fig = pygmt.Figure()
fig.basemap(region=[-90, -70, 0, 20], projection="M15c", frame=True)
fig.coast(shorelines=True)
fig.show()
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

Please paste the output of `python -c "import pygmt; pygmt.show_versions()"`:

```
PyGMT information:
  version: v0.3.1
System information:
  python: 3.9.1 (default, Dec 11 2020, 06:28:49)  [Clang 10.0.0 ]
  executable: /Users/zengxianghang/opt/miniconda3/bin/python
  machine: macOS-10.16-x86_64-i386-64bit
Dependency information:
  numpy: 1.20.2
  pandas: 1.2.3
  xarray: 0.17.0
  netCDF4: 1.5.6
  packaging: 20.9
  ghostscript: 9.53.3
  gmt: 6.1.1
GMT library information:
  binary dir: /Users/zengxianghang/opt/miniconda3/bin
  cores: 8
  grid layout: rows
  library path: /Users/zengxianghang/opt/miniconda3/lib/libgmt.dylib
  padding: 2
  plugin dir: /Users/zengxianghang/opt/miniconda3/lib/gmt/plugins
  share dir: /Users/zengxianghang/opt/miniconda3/share/gmt
  version: 6.1.1```

**Comment by seisman** [comment] 2021-04-02 01:11
If you're running a python script or run the codes in a Python interpreter, you need to use `fig.show(method="external")`.

Duplicate of #366, and should be fixed in #529.

**Closed** 2021-04-02 01:33 UTC
Labels: bug, duplicate

**Comment by Khalilsqu** [comment] 2022-04-16 07:49
I still get  an error!

```
import pygmt

fig = pygmt.Figure()

fig.basemap(region=[-90,-70,0,20], projection="M8i", frame=True)
fig.coast(shorelines=True)

fig.show(method="external")
```

![image](https://user-images.githubusercontent.com/22060413/163666833-2cd19fb5-fa64-490c-90dc-9dea482fe4d4.png)

**Comment by seisman** [comment] 2022-04-16 11:50
> I still get an error!
> 
> ```
> import pygmt
> 
> fig = pygmt.Figure()
> 
> fig.basemap(region=[-90,-70,0,20], projection="M8i", frame=True)
> fig.coast(shorelines=True)
> 
> fig.show(method="external")
> ```
> 
> ![image](https://user-images.githubusercontent.com/22060413/163666833-2cd19fb5-fa64-490c-90dc-9dea482fe4d4.png)

Maybe `fig.show(method="external", waiting=1.0)` works for you. See https://www.pygmt.org/dev/api/generated/pygmt.Figure.show.html for detailed explanations.
