### ISSUE TITLE
Space on labels

### ISSUE THREAD

**Issue by marcelobianchi** [GenericMappingTools/pygmt#388] opened 2020-01-09 12:54 UTC
Dear Developers & Users, 

When plotting data with labels to later building up a legend, the "labels" cannot have spaces. For example, this code:

```Python
F = pygmt.Figure()
F.plot(0,0,B=["x1","y1"],J="X10",S="c0.2",R=[-1,1,-1,1], l = "Super Point")
F.legend(None)
F.show()
```

Fails with the following error code:

```Python
....

    498             raise GMTCLibError(
    499                 "Module '{}' failed with status code {}:\n{}".format(
--> 500                     module, status, self._error_message
    501                 )
    502             )

GMTCLibError: Module 'plot' failed with status code 71:
plot [ERROR]: Error for input file: No such file (Point')
```

When a label is a string without spaces, everything works as expected. This was last tested on version #af26f4.

Kind regards, 

Mb.

**Comment by seisman** [comment] 2020-01-09 14:34
Duplicate of #247. I think currently you have to use `l='"Super Point"'`.

**Closed** 2020-01-10 17:51 UTC
