### ISSUE TITLE
Figure.solar crashes on Linux when drawing nautical terminator for 2024-04-16T06:00:00

### ISSUE THREAD

**Issue by MySlientWind** [GenericMappingTools/pygmt#2959] opened 2024-01-06 13:20 UTC
### Description of the problem

When I try to draw nautical terminator for year=2024, month=4, day=16, hour=6, minute=0, second=0, I got 
```bash
malloc(): invalid size (unsorted)
Aborted (core dumped)
```
There is no problem to draw it for other time, such as year=2024, month=4, day=16, hour=6, minute=1, second=0

### Minimal Complete Verifiable Example

```python
import datetime
import pygmt

fig = pygmt.Figure()
fig.coast(region="d", projection="W0/15c", land="darkgreen", water="lightblue")

terminator_datetime = datetime.datetime(year=2024,
                                        month=4,
                                        day=16,
                                        hour=6,
                                        minute=0,
                                        second=0)

fig.solar(
    terminator="nautical",
    terminator_datetime=terminator_datetime,
    fill="blue@90",
    pen="0.5p",
)

fig.savefig("demo.png")
```

### Full error message

```python-traceback
malloc(): invalid size (unsorted)
Aborted (core dumped)
```

### System information

```bash
PyGMT information:
  version: v0.10.0
System information:
  python: 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0]
  executable: /home/{my_user_name}/software/anaconda3/envs/pygmt/bin/python
  machine: Linux-4.18.0-477.13.1.el8_8.x86_64-x86_64-with-glibc2.28
Dependency information:
  numpy: 1.26.3
  pandas: 2.1.4
  xarray: 2023.12.0
  netCDF4: 1.6.5
  packaging: 23.2
  contextily: None
  geopandas: None
  IPython: 8.19.0
  rioxarray: None
  ghostscript: 9.56.1
GMT library information:
  binary version: 6.4.0
  cores: 80
  grid layout: rows
  image layout: 
  library path: /work/{my_user_name}/anaconda3/envs/pygmt/lib/libgmt.so
  padding: 2
  plugin dir: /work/{my_user_name}/anaconda3/envs/pygmt/lib/gmt/plugins
  share dir: /home/{my_user_name}/software/anaconda3/envs/pygmt/share/gmt
  version: 6.4.0
```

**Comment by seisman** [comment] 2024-01-06 13:47
It works well for me, but I'm using macOS. Could you please add `verbose="d"` to the `Figure.solar` method and post the debugging messages?

**Comment by yvonnefroehlich** [comment] 2024-01-06 13:51
For me, it fails under Linux as reported, but it works under Windows.

**Comment by yvonnefroehlich** [comment] 2024-01-06 15:25
It looks like the issue is related to the `fill` parameter.  If specifying a fill color via `fill` the code fails, but it works if not using `fill` or `fill=None` [Default]. The "problematic" date part seems to be `hour=6, minute=0`.

```python

import datetime
import pygmt

term_datetime = datetime.datetime(
    year=2024,
    month=4,
    day=16,
    hour=6,
    minute=0,  # fails with a fill color
    # minute=1,  # works with a fill color
    second=0,
)
print(term_datetime)

fig = pygmt.Figure()
fig.coast(region="d", projection="W10c", shorelines=True, frame=True)

fig.solar(
    terminator="nautical",
    terminator_datetime=term_datetime,
    # fill=None,  # works
    fill="blue",  # fails
    # pen="1p,red,solid",  # works
)

fig.show()
```

**Comment by seisman** [comment] 2024-01-06 15:31
The equivalent GMT CLI is:
```
gmt solar -Rd -JW10c -Baf -Tn+d2024-04-16T06:00:00 -Gblue -png map
```
Could you please try if it fails for you on Linux?

**Comment by yvonnefroehlich** [comment] 2024-01-06 15:50
> The equivalent GMT CLI is:
> 
> ```
> gmt solar -Rd -JW10c -Baf -Tn+d2024-04-16T06:00:00 -Gblue -png map
> ```
> 
> Could you please try if it fails for you on Linux?

Yes, it fails with GMT 6.4 and 6.4.0_965606f_2022.03.14.
```
(gmt_env_dev) yfroe@gpiseis16:~> gmt solar -Rd -JW10c -Baf -Tn+d2024-04-16T06:00:00 -Gblue -png map
malloc(): invalid size (unsorted)
Aborted (core dumped)
(gmt_env_dev) yfroe@gpiseis16:~> gmt --version
6.4.0_965606f_2022.03.14
```

**Comment by MySlientWind** [comment] 2024-01-06 15:50
Output of `verbose="d"`:
```bash
solar [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
solar [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
solar [DEBUG]: Reset MAP_ANNOT_OBLIQUE to anywhere
solar [DEBUG]: Projected values in meters: -1.80199e+07 1.80199e+07 -9.00996e+06 9.00996e+06
solar [DEBUG]: Computed automatic parameters using dimension scaling: 0.908088
solar [INFORMATION]: Map scale is 2402.66 km per cm or 1:2.40266e+08.
solar [DEBUG]: Running in PS mode modern
solar [DEBUG]: Use PS filename /home/{my_user_name}/.gmt/sessions/gmt_session.852013/gmt_1.ps-
solar [DEBUG]: Append to hidden PS file /home/{my_user_name}/.gmt/sessions/gmt_session.852013/gmt_1.ps-
solar [DEBUG]: Got session name as pygmt-session and default graphics formats as pdf
solar [DEBUG]: Basemap order: Frame = above  Grid = above  Tick/Annot = above
solar [DEBUG]: gmt_get_smallcircle: Added extra point at 0/-90.9758
solar [DEBUG]: gmt_get_smallcircle: Added extra point at 0/-89.0332
solar [DEBUG]: gmtlib_determine_pole: N = 363 Multiples of 360: 0  Residual: -1.27898e-13 Polygon contains south (CW) pole.
solar [INFORMATION]: Plot small circle with pole at 89.9329/10.3111 and radius 102 degrees
solar [DEBUG]: Polar cap: 1
solar [DEBUG]: Try to include S pole in polar cap path
solar [DEBUG]: West longitude = -180.  East longitude = 180
solar [DEBUG]: gmtlib_determine_pole: N = 363 Multiples of 360: 0  Residual: -1.27898e-13 Polygon contains south (CW) pole.
solar [DEBUG]: First longitude = 89.9329.  Last longitude = 89.9329
solar [DEBUG]: Crossing at -180,-90
solar [DEBUG]: k at point closest to lon -180 is = 0 [n = 363]
solar [DEBUG]: Created path from 180/-90 to 180/-90 [0 points]
solar [DEBUG]: Add perimeter data from k0->n [0->363], then 0->k0 [0]
solar [DEBUG]: Add path from -180/-90 to -180/-90 [0 points]
solar [DEBUG]: New path has 364 points, we allocated 363 points
malloc(): invalid size (unsorted)
Aborted (core dumped)
```

Output of 
```bash
gmt solar -Rd -JW10c -Baf -Tn+d2024-04-16T06:00:00 -Gblue -png map
```

```bash
malloc(): invalid size (unsorted)
Aborted (core dumped)
```

**Comment by seisman** [comment] 2024-01-06 15:55
It's likely an upstream bug, although I can't test if it has been fixed in the upcoming GMT 6.5.0 release.

Ping @PaulWessel.

**Comment by PaulWessel** [comment] 2024-01-06 16:01
6.5 master (i.e., release) on macOS arm64:

`gmt solar -Rd -JW10c -Baf -Tn+d2024-04-16T06:00:00 -Gblue -png map`

![map](https://github.com/GenericMappingTools/pygmt/assets/26473567/f458f7b5-ef95-4523-83fd-455f0740a4b6)

**Comment by yvonnefroehlich** [comment] 2024-01-06 17:20
Thanks @PaulWessel for immediately looking at this. So far, this issue appears to be OS-dependent: it works on Windows and macOS, but it fails on Linux.

**Comment by PaulWessel** [comment] 2024-01-06 20:21
So we need someone with Linux to run that command in ddd for example and learn what the crash is and why.

**Comment by seisman** [comment] 2024-01-07 03:32
It still crashes with GMT master branch. Trying to debug it, and this is the callstack and shows where it crashes:
![Screenshot from 2024-01-07 11-30-52](https://github.com/GenericMappingTools/pygmt/assets/3974108/b1bcb247-63ab-447d-8299-ec848f5683f2)

**Comment by PaulWessel** [comment] 2024-01-07 07:23
So it SEGVs in line 565? That is a calloc call but the message says malloc?  What are the values of Belem and size? The message about size is invalid (unsorted) is strange was size is a scalar, no??

**Comment by seisman** [comment] 2024-01-07 07:38
nelem=2048 and size=8.

**Comment by seisman** [comment] 2024-01-07 07:47
Does this debug message make sense to you?
```
solar [DEBUG]: New path has 364 points, we allocated 363 points
```

**Comment by PaulWessel** [comment] 2024-01-07 09:11
Could you try on Linux to change line 9707 in gmt_plot.c to be

	`n_new = 2 * MIN (1, perim_n) + n;`

since perim_n is 0 this is a bit suspect. Does that help?

**Comment by PaulWessel** [comment] 2024-01-07 09:15
Sorry, MAX of course

**Comment by seisman** [comment] 2024-01-07 09:17
Yes, `n_new = 2 * MAX (1, perim_n) + n;` works.

**Comment by seisman** [comment] 2024-01-07 10:11
The upstream bug has been fixed in the GMT's master branch and the working version GMT 6.5.0 will be released soon.

**Closed by seisman** 2024-01-07 10:11 UTC
Labels: bug, upstream
