### ISSUE TITLE
Problem installing on MacOS

### ISSUE THREAD

**Issue by labrosse** [GenericMappingTools/pygmt#722] opened 2020-12-09 11:09 UTC
**Description of the problem**

Fresh install of GMT using the bundle for MacOS (my system is Catalina, 10.15.7). Successfully tested on a simple example. 
Environnement variables set:
echo $GMTHOME
/Applications/GMT-6.1.1.app/Contents/Resources
echo $GMT_LIBRARY_PATH
/Applications/GMT-6.1.1.app/Contents/Resources/lib

pygmt installed using pip (not conda) in a python3 venv. 
python3 --version
Python 3.8.3

**Full code that generated the error**

```python
import pygmt
pygmt.show_versions()
pygmt.test()
```

**Full error message**

```
Traceback (most recent call last):
  File "test2.py", line 1, in <module>
    import pygmt
  File "/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/__init__.py", line 32, in <module>
    _begin()
  File "/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/session_management.py", line 16, in begin
    with Session() as lib:
  File "/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/session.py", line 183, in __enter__
    self.create("pygmt-session")
  File "/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/session.py", line 333, in create
    c_create_session = self.get_libgmt_func(
  File "/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/session.py", line 284, in get_libgmt_func
    self._libgmt = load_libgmt()
  File "/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/loading.py", line 46, in load_libgmt
    raise GMTCLibNotFoundError(
pygmt.exceptions.GMTCLibNotFoundError: Error loading the GMT shared library '/Applications/GMT-6.1.1.app/Contents/Resources/lib/libgmt.dylib':
```

**System information**

Please paste the output of `python -c "import pygmt; pygmt.show_versions()"`:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/__init__.py", line 32, in <module>
    _begin()
  File "/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/session_management.py", line 16, in begin
    with Session() as lib:
  File "/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/session.py", line 183, in __enter__
    self.create("pygmt-session")
  File "/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/session.py", line 333, in create
    c_create_session = self.get_libgmt_func(
  File "/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/session.py", line 284, in get_libgmt_func
    self._libgmt = load_libgmt()
  File "/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/loading.py", line 46, in load_libgmt
    raise GMTCLibNotFoundError(
pygmt.exceptions.GMTCLibNotFoundError: Error loading the GMT shared library '/Applications/GMT-6.1.1.app/Contents/Resources/lib/libgmt.dylib':
```

**Comment by seisman** [comment] 2020-12-09 14:12
Yes, it's a known issue of the GMT macOS bundle. Please see https://github.com/GenericMappingTools/gmt/issues/1930 for discussions.

We recommend you to install pygmt and gmt using `conda`. If you still prefer to use the macOS bundle, you may try the "solution" in this comment https://github.com/GenericMappingTools/gmt/issues/1930#issuecomment-698683500.

**Comment by seisman** [comment] 2020-12-25 05:12
Closing the issue as it's a duplicate of upstream bug https://github.com/GenericMappingTools/gmt/issues/1930

**Closed by seisman** 2020-12-25 05:12 UTC
Labels: bug, upstream
