### ISSUE TITLE
Unclear structure of navigation bar of PyGMT website

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2042] opened 2022-08-06 11:58 UTC
When looking at the navigation bar on the left side of the [PyGMT website](https://www.pygmt.org/dev/index.html), I am wondering why in the USER GUIDE part the last sub-point of a section contains _all_ sub-points of this section as sub-sub-points:

![pygmt_website_tutorials](https://user-images.githubusercontent.com/94163266/183246107-1f90d83a-39aa-4f41-a9c6-7061e9f13eea.png)

![pygmt_website_gallery](https://user-images.githubusercontent.com/94163266/183246122-38a9762b-8e4e-42be-9770-543003f68b06.png)

![pygmt_website_projections](https://user-images.githubusercontent.com/94163266/183246126-8cc93fb5-f448-4064-b016-71cac9886e20.png)

I think this makes no sense and the navigation bar should be restructured in the way that the example lists are shifted to the respective sub-point, e.g.:

<img src="https://user-images.githubusercontent.com/94163266/183247047-ac9ac8ac-34e4-4542-aca1-de7a738bc407.png" height="500">

**Comment by seisman** [comment] 2022-08-06 14:21
I don't see the problem in [the v0.7.0 documentation](https://www.pygmt.org/v0.7.0/tutorials/index.html). I think it's likely caused by bugs or incompatible changes in the recent release of sphinx-gallery (https://github.com/sphinx-gallery/sphinx-gallery/releases/tag/v0.11.0).

**Comment by yvonnefroehlich** [comment] 2022-08-07 21:44
Our issue seems similar to issue https://github.com/sphinx-gallery/sphinx-gallery/issues/935. The problem seems to be related to changes in PR https://github.com/sphinx-gallery/sphinx-gallery/pull/904. But it should be fixed in PR https://github.com/sphinx-gallery/sphinx-gallery/pull/944, which is in the last release [v0.11.0](https://github.com/sphinx-gallery/sphinx-gallery/releases/tag/v0.11.0) of sphinx-gallery. Maybe / probably there is a relation to https://github.com/sphinx-gallery/sphinx-gallery/pull/944#issuecomment-1175227862. And we have to adjust the `conf.py` file in the way that  `nested_sections=False`.
Please note, until now I did not totally understand what they wanted to change or improve in PR https://github.com/sphinx-gallery/sphinx-gallery/pull/904.

**Comment by seisman** [comment] 2022-08-08 15:48
> Maybe / probably there is a relation to [sphinx-gallery/sphinx-gallery#944 (comment)](https://github.com/sphinx-gallery/sphinx-gallery/pull/944#issuecomment-1175227862). And we have to adjust the `conf.py` file in the way that `nested_sections=False`.

Could you please make a PR with `nested_sections=False` and see if it works as we expect?

**Comment by yvonnefroehlich** [comment] 2022-08-19 05:20
Unfortunately, there is still or now another small error in the structure of the navigation bar. Under the section [Projection Table](https://www.pygmt.org/dev/projections/index.html) the sub-subsection for the Non-geographic Projections are listed or repeated:

![gallery_navbar_ProjectionTable_afterbugfix](https://user-images.githubusercontent.com/94163266/185547414-df56e29e-3332-4fb5-b0a7-ca2cf72efc12.png)

**Comment by seisman** [comment] 2023-03-26 07:44
The issue may have been fixed in the latest sphinx-gallery releases and the navigation bar looks good in our dev documentation (https://www.pygmt.org/dev/projections/index.html#projection-table).

Closing the issue now. Please reopen it if you find any other similar issues.

**Closed by seisman** 2023-03-26 07:44 UTC
Labels: maintenance
