### ISSUE TITLE
Gallery plots for each projection

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/pygmt#292] opened 2019-03-12 04:35 UTC
**Description of the desired feature**

The user documentation contains a [gallery of projections available](https://www.pygmt.org/dev/projections/index.html). The plots showcase the projection so it's easy to choose which one you want (by clicking an image instead of having to google the name). **We need to fill out this gallery** with all projections listed in https://www.generic-mapping-tools.org/gmt/latest/proj_codes_GMT.html 

To make a gallery plot, place a script that generates the figure in `examples/projections` and sphinx-gallery will take care of the rest. The file must have a specific format (see the other examples). Ideally, each projection should show a case in which it's ideal (e.g. not using Mercator for high latitudes).

Any help with this is greatly appreciated! We can build this out slowly, one example at a time.

**Comment by DefUs3r** [comment] 2019-03-12 06:59
Sir,
I would like to take up this issue. I am a beginner and I have no idea of the codebase and a very slight idea of what this library does. I would like to make my first commit here. Can you help me out?

**Comment by seisman** [comment] 2019-03-15 19:31
There is a chapter "[GMT Map Projections](https://www.generic-mapping-tools.org/gmt/latest/GMT_Docs.html#gmt-map-projections
)" in the GMT cookbook. We can copy the examples.

**Comment by leouieda** [comment] 2019-03-15 20:01
Thanks, @seisman. I was wondering where that was. I want to try this out here and hopefully copy some of it over to the GMT docs later on.

**Comment by leouieda** [comment] 2019-03-15 20:04
:wave: Hi @DefUs3r, thanks for offering to help! Please have a look at our [Contributing Guide](CONTRIBUTING.md). You will need at least a bit of mapping knowledge, though, since the goal is to write example scripts.

**Comment by xibalba01** [comment] 2019-07-19 10:44
I have a background in geoinformatics and i am slightly familiar with projections so i would like to give this a try. The plots would need to be created with pyGMT right? And the commands used would be the ones from the GMT Map Projections page @seisman mentioned?

**Comment by leouieda** [comment] 2019-07-27 17:12
Hi @xibalba01 we don't mind PRs at all :slightly_smiling_face: I agree that having a small description of when the projection should be used would be very helpful!

**Comment by xibalba01** [comment] 2019-07-28 08:44
I have problems building the docs under windows:

Running `make all` or `make html` yields in:
```
(pygmt) C:\Users\mo3kLo4r\Documents\Code\OpenSource\pygmt\doc>make all
ECHO ist ausgeschaltet (OFF).
"Building API docs."
ECHO ist ausgeschaltet (OFF).
sphinx-autogen -i -t _templates -o api/generated api/*.rst
[autosummary] generating autosummary for: api/*.rst
[autosummary] writing to api/generated
Traceback (most recent call last):
  File "C:\Users\mo3kLo4r\Miniconda3\envs\pygmt\Scripts\sphinx-autogen-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\mo3kLo4r\Miniconda3\envs\pygmt\lib\site-packages\sphinx\ext\autosummary\generate.py", line 421, in main
    app=app)
  File "C:\Users\mo3kLo4r\Miniconda3\envs\pygmt\lib\site-packages\sphinx\ext\autosummary\generate.py", line 137, in generate_autosummary_docs
    items = find_autosummary_in_files(sources)
  File "C:\Users\mo3kLo4r\Miniconda3\envs\pygmt\lib\site-packages\sphinx\ext\autosummary\generate.py", line 253, in find_autosummary_in_files
    errors='ignore') as f:
  File "C:\Users\mo3kLo4r\Miniconda3\envs\pygmt\lib\codecs.py", line 898, in open
    file = builtins.open(filename, mode, buffering)
OSError: [Errno 22] Invalid argument: 'api/*.rst'
make: *** [api] Fehler 1
```
A short workaround was to not use `api/*.rst` and instead use index.rst explicitly from the `api/` folder, but then i get another error when trying to build the html pages:

```
(pygmt) C:\Users\mo3kLo4r\Documents\Code\OpenSource\pygmt\doc>make html
ECHO ist ausgeschaltet (OFF).
"Building API docs."
ECHO ist ausgeschaltet (OFF).
sphinx-autogen -i -t _templates -o api/generated api/index.rst
[autosummary] generating autosummary for: api/index.rst
[autosummary] writing to api/generated
ECHO ist ausgeschaltet (OFF).
"Building HTML files."
ECHO ist ausgeschaltet (OFF).
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.8.5
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from http://pandas.pydata.org/pandas-docs/stable/objects.inv...
intersphinx inventory has moved: http://pandas.pydata.org/pandas-docs/stable/objects.inv -> https://pandas.pydata.org/pandas-docs/stable/objects.inv
loading intersphinx inventory from http://xarray.pydata.org/en/stable/objects.inv...
generating gallery...
Der Befehl "gswin64c" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
WARNING: C:\Users\mo3kLo4r\Documents\Code\OpenSource\pygmt\examples\gallery\coast\borders.py failed to execute correctly: Traceback (most recent call last):
  File "C:\Users\mo3kLo4r\Miniconda3\envs\pygmt\lib\site-packages\sphinx_gallery\gen_rst.py", line 480, in _memory_usage
    out = func()
  File "C:\Users\mo3kLo4r\Miniconda3\envs\pygmt\lib\site-packages\sphinx_gallery\gen_rst.py", line 465, in __call__
    exec(self.code, self.globals)
  File "C:\Users\mo3kLo4r\Documents\Code\OpenSource\pygmt\examples\gallery\coast\borders.py", line 25, in <module>
    fig.show()
  File "c:\users\mo3klo4r\documents\code\opensource\pygmt\pygmt\figure.py", line 272, in show
    fmt="png", dpi=dpi, anti_alias=True, as_bytes=True, transparent=True
  File "c:\users\mo3klo4r\documents\code\opensource\pygmt\pygmt\figure.py", line 342, in _preview
    self.savefig(fname, dpi=dpi, **kwargs)
  File "c:\users\mo3klo4r\documents\code\opensource\pygmt\pygmt\figure.py", line 225, in savefig
    self.psconvert(prefix=prefix, fmt=fmt, crop=crop, **kwargs)
  File "c:\users\mo3klo4r\documents\code\opensource\pygmt\pygmt\helpers\decorators.py", line 187, in new_module
    return module_func(*args, **kwargs)
  File "c:\users\mo3klo4r\documents\code\opensource\pygmt\pygmt\helpers\decorators.py", line 282, in new_module
    return module_func(*args, **kwargs)
  File "c:\users\mo3klo4r\documents\code\opensource\pygmt\pygmt\figure.py", line 165, in psconvert
    lib.call_module("psconvert", build_arg_string(kwargs))
  File "c:\users\mo3klo4r\documents\code\opensource\pygmt\pygmt\clib\session.py", line 490, in call_module
    module, status, self._error_message
pygmt.exceptions.GMTCLibError: Module 'psconvert' failed with status code 78:
psconvert [ERROR]: Error opening HKLM key
psconvert [ERROR]: Failed to parse response to GhostScript version query [n = -1 0 0].

psconvert [ERROR]: Error opening HKLM key
Der Befehl "gswin64c" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
psconvert [ERROR]: Failed to parse response to GhostScript version query [n = -1 0 0].

Exception occurred:
  File "c:\users\mo3klo4r\documents\code\opensource\pygmt\pygmt\clib\session.py", line 490, in call_module
    module, status, self._error_message
pygmt.exceptions.GMTCLibError: Module 'psconvert' failed with status code 78:
psconvert [ERROR]: Error opening HKLM key
psconvert [ERROR]: Failed to parse response to GhostScript version query [n = -1 0 0].
The full traceback has been saved in C:\Users\mo3kLo4r\AppData\Local\Temp\sphinx-err-_hpy72rb.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Fehler 2
```

Somehow psconvert can't find ghostscript even though its installed... Strange, since normal plotting within a jupyter notebook works. In the beginning i didnt had ghostscript installed so no plot worked and i got the same error. Any ideas?

**Comment by xibalba01** [comment] 2019-07-28 09:27
Under linux when running `make html` i get the following error:

```
$ make html

Building API docs.

sphinx-autogen -i -t _templates -o api/generated api/index.rst
[autosummary] generating autosummary for: api/index.rst
[autosummary] writing to api/generated

Building HTML files.

sphinx-build -b html -d _build/doctrees   . _build/html
Sphinx v1.8.5 in Verwendung
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from http://pandas.pydata.org/pandas-docs/stable/objects.inv...
intersphinx inventory has moved: http://pandas.pydata.org/pandas-docs/stable/objects.inv -> https://pandas.pydata.org/pandas-docs/stable/objects.inv
loading intersphinx inventory from http://xarray.pydata.org/en/stable/objects.inv...
generating gallery...
Error: /undefined in 0,06llery/coast... [ 33%] borders.py                                                                                                                                                  
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   2045   1   3   %oparray_pop   2044   1   3   %oparray_pop   2025   1   3   %oparray_pop   1884   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:957/1684(ro)(G)--   --dict:0/20(G)--   --dict:77/200(L)--   --dict:148/250(L)--
Current allocation mode is local
Last OS error: No such file or directory
Current file position is 19656
Makefile:35: recipe for target 'html' failed
make: *** [html] Speicherzugriffsfehler
```

**Comment by xibalba01** [comment] 2019-07-28 10:59
Running `sphinx-build -b html -d _build/doctrees   . _build/html -v` by hand yields additional information about psconvert (still on linux):

```
Output from /home/mo3klo4r/Desktop/pygmt/examples/gallery/coast/borders.py
psconvert [ERROR]: System call [gs -q -dSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true '/home/mo3klo4r/.gmt/sessions/gmt6.15252/gmt_1.ps-' 2> '/home/mo3klo4r/.gmt/sessions/gmt6.15252/psconvert_15252c.bb'] returned error 256.
```

**Comment by xibalba01** [comment] 2019-07-28 11:57
I found out that the `Error: /undefined in 0,06` is related to decimal numbers with a comma instead of a period. I manually searched for the 0,06 in the ps-file and replaced the comma with a period. A couple of other lines had this problem. After editing the ps-file by hand the above command works without any error and returns bounding box information: 

```
$ gs -q -dSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true '/home/mo3klo4r/.gmt/sessions/gmt6.15252/gmt_1.ps-'
%%BoundingBox: 319 338 977 954
%%HiResBoundingBox: 319.211990 338.705990 976.967970 953.621971
```
I am wondering where this error is coming from because normal plots within a notebook work. The gallery generation code just calls fig.show() from the examples scripts IIRC?! Maybe it comes from one level deeper, the shared gmt library?!? Are you able to reproduce this? I am using GMT in version 6.1.0_eb12eba_2019.07.19 and Ghostscript 9.26

Another thought was, that this is a locale issue since i am from germany, where sometimes you have problems with decimal delimiters... but i don't know at all...

Here is the diff generated from the fixed postscript file and another broken one that returned the aforementioned error, sorry for so much text :):

```diff
$ git diff /home/mo3klo4r/.gmt/sessions/gmt6.15191/gmt_1.ps- /home/mo3klo4r/.gmt/sessions/gmt6.15252/gmt_1.ps- 
diff --git a/home/mo3klo4r/.gmt/sessions/gmt6.15191/gmt_1.ps- b/home/mo3klo4r/.gmt/sessions/gmt6.15252/gmt_1.ps-
index 3ec4b0f..5f78564 100644
--- a/home/mo3klo4r/.gmt/sessions/gmt6.15191/gmt_1.ps-
+++ b/home/mo3klo4r/.gmt/sessions/gmt6.15252/gmt_1.ps-
@@ -1,11 +1,11 @@
 %!PS-Adobe-3.0
 %%BoundingBox: 0 0 32767 32767
-%%HiResBoundingBox: 0 0 32767,0000 32767,0000             
+%%HiResBoundingBox: 0 0 32767,0000 32767,0000
 %%Title: GMT v6.1.0_eb12eba_2019.07.19 [64-bit] Document from psbasemap
 %%Creator: GMT6
 %%For: unknown
 %%DocumentNeededResources: font Helvetica
-%%CreationDate: Sun Jul 28 12:31:56 2019
+%%CreationDate: Sun Jul 28 12:32:17 2019
 %%LanguageLevel: 2
 %%DocumentData: Clean7Bit
 %%Orientation: Portrait
@@ -652,7 +652,7 @@ PSLevel 1 gt { << /PageSize [32767 32767] /ImagingBBox null >> setpagedevice } i
 %%Page: 1 1
 
 %%BeginPageSetup
-V 0,06 0,06 scale
+V 0.06 0.06 scale
 %%EndPageSetup
 
 /PSL_page_xsize 546117 def
@@ -673,7 +673,7 @@ O0
 %%BeginObject PSL_Layer_1
 0 setlinecap
 0 setlinejoin
-3,32551 setmiterlimit
+3.32551 setmiterlimit
 25 W
 4 W
 2392 0 M
@@ -1751,7 +1751,7 @@ O0
 %%BeginObject PSL_Layer_2
 0 setlinecap
 0 setlinejoin
-3,32551 setmiterlimit
+3.32551 setmiterlimit
 2741 9582 M
 -1 -3 D
 -13 -7 D
@@ -1763,7 +1763,7 @@ P
 2782 9569 M
 -12 -5 D
 P
-{0,745 A} FS
+{0.745 A} FS
 FO
 2711 9582 M
 11 -4 D
@@ -12243,7 +12243,7 @@ P
 0 1 D
 -10 -31 D
 P
-{0,745 A} FS
+{0.745 A} FS
 FO
 6005 8080 M
 -5 13 D
@@ -21155,7 +21155,7 @@ P
 6 -5 D
 -4 -2 D
 P
-{0,745 A} FS
+{0.745 A} FS
 FO
 8023 4791 M
 -10 -8 D
```

**Comment by xibalba01** [comment] 2019-07-28 12:31
Man i am so sorry for spamming this issue so much... i fixed building the docs by running `LC_NUMERIC=en_US.UTF-8`... Damn german systems, and also my lack of linux knownledge.... But now i can start working fully on the examples and docs page under linux!

**Comment by xibalba01** [comment] 2019-07-29 11:37
I split the projections folder into the main groups by creating subfolders with their own README.txt like it is described in the sphinx-gallery-docs. Now it appears like i was thinking it makes the most sense, but the menu on the left side does not split up into projections like expected. It would expect that not for every projections section there is a new menu point but instead when clicking on projections the sub sections would pop up and by again clicking on them they expand to show the single projections...

![projections_gallery (1)](https://user-images.githubusercontent.com/37411699/62045517-d2a32a80-b205-11e9-9231-de0f7b40b900.png)

**Comment by willschlitzer** [comment] 2020-12-08 20:54
I'll work on this.

**Comment by willschlitzer** [comment] 2020-12-09 16:20
Should the different projections have a particular and standardized color scheme? The GMT docs don't seem to follow any standard color scheme, but all of the PyGMT projection examples have gray land and white water.

**Comment by seisman** [comment] 2020-12-09 16:35
I don't think we have any standardized color scheme here. I actually prefer the maps in the GMT docs.

**Comment by willschlitzer** [comment] 2020-12-09 19:42
I prefer them as well. My thought is to copy the GMT example projection maps when able, as I think they are all good maps and there's no need to reinvent the wheel. I just want to make sure there isn't a plan in place already for standardized example projection maps.

**Comment by willschlitzer** [comment] 2020-12-10 08:32
I think it would be a good idea to have the home page of the projection gallery have some sort of table that lists the different projection codes. Even when the gallery is fleshed out, it won't be immediately clear to someone looking at PyGMT code what the given projection is, and this will keep them from having to click on all of the gallery examples to find out. I looked through the PyGMT docs to see if there are any examples of a table but couldn't find one; any ideas on how to implement this?

**Comment by willschlitzer** [comment] 2020-12-16 21:17
Are we missing any examples for gallery plots?

**Comment by seisman** [comment] 2020-12-17 03:32
@willschlitzer Thanks again for your recent contributions! I think this issue is close to finishing. 

I think it would be better to also add [logarithmic projection](https://docs.generic-mapping-tools.org/latest/cookbook/coordinate-transformations.html#cartesian-logarithmic-projection) and [power projection](https://docs.generic-mapping-tools.org/latest/cookbook/coordinate-transformations.html#cartesian-power-projection).

**Comment by seisman** [comment] 2020-12-17 15:23
> I think it would be a good idea to have the home page of the projection gallery have some sort of table that lists the different projection codes. Even when the gallery is fleshed out, it won't be immediately clear to someone looking at PyGMT code what the given projection is, and this will keep them from having to click on all of the gallery examples to find out. I looked through the PyGMT docs to see if there are any examples of a table but couldn't find one; any ideas on how to implement this?

@willschlitzer Sounds a good idea. Could you open a new issue for this so that we can better discuss it?

**Comment by phloose** [comment] 2020-12-17 22:36
Before you close this issue i would like to add that it would be nice to have some explanatory text about each projection like in the [GMT cookbook ](https://docs.generic-mapping-tools.org/latest/cookbook/map-projections.html). I [proposed](https://github.com/GenericMappingTools/pygmt/issues/292#issuecomment-513183815) and started this with #318 and would think that this is very useful for people new to GMT and mapping, because projections are not easy to grasp for everyone.

**Comment by willschlitzer** [comment] 2020-12-18 08:07
Would we be able to copy the text directly from the GMT cookbook on the reasoning behind using different projections? I don't want to plagiarize, but I would also hope to avoid reinventing the wheel if possible.

**Comment by seisman** [comment] 2020-12-18 08:15
> I don't want to plagiarize, but I would also hope to avoid reinventing the wheel if possible.

PyGMT and GMT belong to the same organization, so don't worry about plagiarization. We can just copy and paste from the cookbook, and even improve it if someone knows more about projections.

Again, it would be good if @willschlitzer can open a new issue for your comment https://github.com/GenericMappingTools/pygmt/issues/292#issuecomment-742367645, and @phloose for your comment https://github.com/GenericMappingTools/pygmt/issues/292#issuecomment-747743344, as I don't want to make the discussions too long in this issue.

**Closed** 2020-12-23 15:57 UTC
Labels: documentation, good first issue, help wanted, scipy-sprint
